- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline"
- pipeline.id: jtl-csv
  path.config: "/usr/share/logstash/pipeline-in-csv"
  pipeline.workers: 1
  pipeline.batch.size: 1
  pipeline.ordered: "true"