# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# This is a basic workflow to help you get started with Actions

name: Build & check file docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output: [elasticsearch, influxdb]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # printenv
      - name: printenv
        run: printenv

      # PWD
      - name: PWD
        run: pwd

      # Runs a set of commands using the runners shell
      - name: Build Images
        run: |
          docker build -f docker/${{ matrix.output }}/Dockerfile . -t logstash/jmeter/${{ matrix.output }}

        # Run docker
      - name: Check Image
        run: |
          docker run --rm  logstash/jmeter/${{ matrix.output }} -t
