# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PATH_OUT: build/out
      PATH_IN: testing/file/in
      PATH_EXPECTED: testing/file/expected

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # printenv
      - name: printenv
        run: printenv

      # PWD
      - name: PWD
        run: pwd

      # install jq
      - name: apt jq
        run: sudo apt-get install -y jq

      # Runs a set of commands using the runners shell
      - name: prepare build folders
        run: |
          mkdir build
          cp -r config build
          cp -r testing/config/* build/config/
          rm build/config/pipeline/output-elastic-logstash.conf
          mkdir $PATH_OUT
          chmod +777 $PATH_OUT
          ls -lah build/config/pipeline

       # Run docker
      - name: Run docker
        run: |
          docker run --rm -e "FILE_READ_MODE=read" -e "FILE_START_POSITION=beginning" -e "FILE_EXIT_AFTER_READ=true" -v ${PWD}/$PATH_OUT:/output/ -v ${PWD}/$PATH_IN:/input/ -v ${PWD}/build/config/pipeline:/usr/share/logstash/pipeline/ -v ${PWD}/build/config/settings/logstash.yml:/usr/share/logstash/config/logstash.yml docker.elastic.co/logstash/logstash:7.13.2

      - name: check easy-admin-20211018-082256
        run: |
         
          for filepath in $PATH_EXPECTED/*.json; do
                 FILE_NAME=${filepath##*/}
                 echo ####START###############$FILE_NAME#####################
                 EXPECTED_FILE=$PATH_EXPECTED/$FILE_NAME
                 OUT_FILE=$PATH_OUT/$FILE_NAME
                 cat $OUT_FILE
                 diff <(jq --sort-keys 'del(.host) or del(."@timestamp")' $EXPECTED_FILE) <(jq --sort-keys 'del(.host) or del(."@timestamp")' $OUT_FILE)
                 echo ####END###############$FILE_NAME#####################
          done

 


